version: '3.3'

services:
        firebird:
                image: carlesbarreda/firebird:latest
                container_name: firebird
                hostname: firebird
                ports:
                        - "3050:3050/tcp"
                volumes:
                        - databases:/srv/firebird

volumes:
    databases: {}