name: Build carlesbarreda/firebird:2.5.9

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/386,linux/arm64,linux/arm/v7 \
            --tag carlesbarreda/firebird:2.5.9 \
            --tag carlesbarreda/firebird:latest \
            --push .